<?php

namespace App\Services\SocketChat;

use Ratchet\ConnectionInterface;
use SplObjectStorage;

class SocketChatService extends SocketChatAbstract
{
    protected $users;

    public function __construct()
    {
        $this->users = new SplObjectStorage;
    }

    public function onOpen(ConnectionInterface $conn)
    {
        parent::onOpen($conn);

        $this->users->attach($conn);

        echo "New user " . $conn->resourceId . " connected\n";
    }

    public function onClose(ConnectionInterface $conn)
    {
        parent::onClose($conn); // TODO: Change the autogenerated stub

        $this->users->detach($conn);

        echo "User " . $conn->resourceId . " disconnected\n";
    }

    public function onMessage(ConnectionInterface $from, $msg)
    {
        parent::onMessage($from, $msg);

        $userRequestMessage = count($this->users) - 1;

        echo $from->resourceId . ' ' . $msg . ' ' . $userRequestMessage;

        foreach ($this->users as $user) {
            if ($from != $user) {
                $user->send($msg);
            }
        }
    }

    public function onError(ConnectionInterface $conn, \Exception $e)
    {
        parent::onError($conn, $e); // TODO: Change the autogenerated stub

        echo 'Error ' . $e->getMessage();

        $conn->close();
    }
}
